/* GENERADO por web/scripts/extraer-ingles-app.mjs desde src/lib/i18n.ts: no se edita a mano.
   Las parejas del diccionario de la app que usa la maqueta. Lo aplica demo/traducir.js. */
window.DEMO_EN = Object.assign(window.DEMO_EN || {}, {
  "↑↓ para moverte · Enter para ir · Esc para cerrar": "↑↓ to move · Enter to go · Esc to close",
  "＋ Nuevo proyecto": "＋ New project",
  "✦ Capataz": "✦ Foreman",
  "abierta ahora": "open right now",
  "ábreme las sesiones del panel de Orquio": "open the sessions of the Orquio dashboard",
  "Abrir": "Open",
  "Abrir el archivo": "Open the file",
  "Abrir su web": "Open its site",
  "Abrir una sesión": "Open a session",
  "Abrir una terminal": "Open a terminal",
  "Actividad": "Activity",
  "agente": "agent",
  "agentes": "agents",
  "ahora": "now",
  "Ahora": "Now",
  "ahora mismo": "just now",
  "Ajustes": "Settings",
  "al final": "at the end",
  "Antes": "Before",
  "Añadir": "Add",
  "Añadir cuenta": "Add account",
  "Apartadas": "Set aside",
  "Apartar todas las terminales: siguen vivas en la tira de abajo": "Set every terminal aside: they stay alive in the strip below",
  "Archivos": "Files",
  "Arriba": "Top",
  "Asistente": "Assistant",
  "Aún en pie": "Still up",
  "ayer": "yesterday",
  "Ayer": "Yesterday",
  "Bajar": "Move down",
  "Buenas noches": "Good evening",
  "Buenas tardes": "Good afternoon",
  "Buenos días": "Good morning",
  "Buscar conversaciones…": "Search conversations…",
  "Buscar en tus notas": "Search your notes",
  "Buscar skill": "Search skill",
  "Buscar un comando": "Search for a command",
  "Cabina": "Cockpit",
  "Calendario": "Calendar",
  "Cambiar bóveda": "Change vault",
  "Capa": "Layer",
  "Capataz": "Foreman",
  "Captura": "Screenshot",
  "capturas": "screenshots",
  "Carpeta": "Folder",
  "Carpetas": "Folders",
  "Centro": "Center",
  "Cerrar": "Close",
  "Cerrar todas": "Close all",
  "Claves de API": "API keys",
  "cogida": "picked",
  "Color": "Colour",
  "Comandos": "Commands",
  "con ella nacen las terminales nuevas": "new terminals open with it",
  "conectada": "connected",
  "conectadas": "connected",
  "Contexto": "Context",
  "Crear": "Create",
  "Cuenta": "Account",
  "Cuentas": "Accounts",
  "cuentas conectadas": "accounts connected",
  "de pago": "paid",
  "Descargar": "Download",
  "Disposición": "Layout",
  "Dividir el panel a la derecha": "Split the pane to the right",
  "documento": "document",
  "documentos": "documents",
  "Donde más se ha trabajado esta semana. Clic para ir.": "Where most of the work happened this week. Click to jump.",
  "el límite más apretado": "tightest limit",
  "Emisión": "Streaming",
  "en Layco: Antigravity al frontend y un Claude al backend": "in Layco: Antigravity on the frontend and a Claude on the backend",
  "en un panel": "in a pane",
  "enlace": "link",
  "enlaces": "links",
  "entrada": "input",
  "Enviar": "Send",
  "Escribe aquí. Enter envía, Mayús+Enter hace un párrafo.": "Type here. Enter sends, Shift+Enter starts a paragraph.",
  "Escribir el encargo": "Write the brief",
  "esperando": "waiting",
  "esta semana": "this week",
  "Esta semana": "This week",
  "Filtrar proyectos": "Filter projects",
  "Filtrar proyectos y sesiones": "Filter projects and sessions",
  "Fondo": "Background",
  "gratis": "free",
  "guía": "guide",
  "hecha": "done",
  "Hecho": "Done",
  "hoy": "today",
  "Hoy": "Today",
  "instalado": "installed",
  "Izquierda": "Left",
  "La cabecera": "The header",
  "lang": "es",
  "Lienzo": "Canvas",
  "Limpio": "Clean",
  "líneas": "lines",
  "Llamar al Asistente": "Call the Assistant",
  "Lo que Adeorq está gastando en tu equipo": "What Adeorq is costing your machine",
  "Logo y nombre": "Logo and name",
  "Maximizar": "Maximise",
  "Mayús": "Shift",
  "Memoria": "Memory",
  "mes": "month",
  "Minimizar todas": "Minimise all",
  "Minimizar: baja a la tira de abajo y sigue trabajando": "Minimise: drops to the strip below and keeps working",
  "Mirar": "Look",
  "Misión": "Mission",
  "Nace con": "Born with",
  "nada pendiente de ti": "nothing on your plate",
  "No encuentro eso.": "Nothing matches that.",
  "no está": "not here",
  "No instalados": "Not installed",
  "Nombre del proyecto": "Project name",
  "Nota": "Note",
  "notas": "notes",
  "Nueva conversación": "New conversation",
  "o": "or",
  "objetivo": "goal",
  "Objetivos de hoy": "Today's goals",
  "Panel": "Dashboard",
  "Parar": "Stop",
  "paso": "step",
  "Planear": "Plan it",
  "Por hacer": "To do",
  "por millón": "per million",
  "Preguntando a Claude…": "Asking Claude…",
  "proyectos": "projects",
  "Proyectos": "Projects",
  "Proyectos calientes": "Hot projects",
  "puesto": "post",
  "puestos": "posts",
  "Qué quieres hacer": "What do you want to do",
  "Recientes": "Recent",
  "Repartir": "Split them",
  "Repartir las terminales en una plantilla": "Deal the terminals into a template",
  "resultado": "result",
  "resultados": "results",
  "se renueva": "renews",
  "semana": "week",
  "sesión": "session",
  "sesión abierta ahora": "session open right now",
  "sesiones": "sessions",
  "Sesiones": "Sessions",
  "sesiones esta semana": "sessions this week",
  "sí": "yes",
  "Siguiente": "Next",
  "sin subagentes fuera": "no subagents out",
  "Skills · Uso": "Skills · Usage",
  "Solo los logos, en grande": "Logos only, big",
  "Suave": "Smooth",
  "suelta": "loose",
  "suyo": "theirs",
  "Tapar esta terminal (para emitir)": "Cover this terminal (for streaming)",
  "tarea": "task",
  "te espera": "waiting for you",
  "Te espera": "Waiting on you",
  "te esperan": "waiting for you",
  "te pregunta": "is asking you",
  "te pregunta algo": "is asking you something",
  "Tema": "Theme",
  "Terminal con esta": "Terminal with this one",
  "terminales": "terminals",
  "Tiene una sesión abierta ahora mismo": "It has a session open right now",
  "Todo": "All",
  "trabajando": "working",
  "trabajando ahora": "working now",
  "Traerla de vuelta al mosaico": "Bring it back to the mosaic",
  "Tus cuentas": "Your accounts",
  "Tus objetivos de hoy": "Your goals for today",
  "usa": "uses",
  "Ver": "View",
  "Ver la web en un panel (localhost)": "See the site in a pane (localhost)",
  "viva": "live",
  "Volver": "Back",
  "Volver a mirar": "Look again",
  "vuelta": "lap",
  "vueltas": "laps",
});
