/* Adeorq · demo/en.js
   El inglés de lo que es solo de la maqueta (conversaciones, terminales, notas,
   temas, avisos). Lo de la app viene de en-app.js; los dos los aplica
   demo/traducir.js. Las claves son el texto español EXACTO de un nodo de texto
   o de un title, placeholder o aria-label; las frases partidas en trozos se
   traducen trozo a trozo, en el mismo orden. */
window.DEMO_EN = Object.assign(window.DEMO_EN || {}, {
  /* La Cabina: el panel de Claude Code */
  '› échale un ojo a la barra de arriba, que algo no me cuadra': '› take a look at the top bar, something\'s off',
  'Cuenta nueve pestañas y el corte de la barra sigue puesto para ocho.': 'It counts nine tabs, and the bar\'s breakpoint is still set for eight.',
  '└ Escrita de corrida la fila entera necesita 1.968 px, medido.': '└ Laid out in one line, the whole row needs 1,968 px, measured.',
  '└ El corte está en 1.700, así que entre esos dos «Cerrar todas» se sale sin recortarse.': '└ The breakpoint is at 1,700, so between those two widths "Close all" overflows instead of getting trimmed.',
  '└ src/App.css · 1 línea': '└ src/App.css · 1 line',
  '› ¿puedes repasar el contraste de la landing?': '› can you go over the contrast on the landing page?',
  'He mirado las tres capas que se pisaban.': 'I checked the three overlapping layers.',
  '└ El texto sobre la foto no llegaba al mínimo legible: 3,1:1 medido.': '└ The text over the photo didn\'t reach the legibility minimum: 3.1:1, measured.',
  '└ Arreglado con una sombra, sin tocar el tono del tema.': '└ Fixed with a shadow, without touching the theme\'s tone.',
  '└ web/styles/hero.css · 4 líneas': '└ web/styles/hero.css · 4 lines',
  '› y el aviso de sesión cara, ¿por qué no saltaba?': '› and the expensive-session warning, why wasn\'t it firing?',
  'Iba por porcentaje, y con la ventana de un millón de tokens no habría saltado hasta los 600.000.': 'It went by percentage, and with a one-million-token window it wouldn\'t have fired until 600,000.',
  '└ Ahora avisa a los 150.000, que es donde empieza a doler.': '└ Now it warns at 150,000, which is where it starts to hurt.',
  '└ src/components/TerminalPane.tsx · 2 líneas': '└ src/components/TerminalPane.tsx · 2 lines',

  /* La Cabina: PowerShell, Codex y cargo test */
  'app abierta en 1,2 s · motor ConPTY listo · 4 terminales': 'app open in 1.2 s · ConPTY engine ready · 4 terminals',
  'La web · Codex': 'The website · Codex',
  'Build verificado. Ábrela en http://localhost:5173/ para verlo.': 'Build verified. Open http://localhost:5173/ to see it.',
  '› dale una vuelta al encuadre de la portada': '› take another pass at the front page framing',
  'Hecho: el logo respira y el titular ya no se parte en dos.': 'Done: the logo has room to breathe and the headline no longer breaks in two.',
  '¿Lo dejo así o pruebo con la foto a sangre?': 'Shall I leave it like this or try the photo full-bleed?',
  'cargo test · el motor': 'cargo test · the engine',
  '› pásale las pruebas al motor antes de que lo toque nadie más': '› run the tests on the engine before anyone else touches it',
  'Voy. Lanzo la tanda entera y te digo qué se cae.': 'On it. I\'ll run the whole batch and tell you what breaks.',
  '✳ 31 pasados · 1 fallando · 2 corriendo': '✳ 31 passed · 1 failing · 2 running',
  'El fallo es de la prueba, no del motor: cuenta cinco sesiones y una es un daemon de fondo.': 'The bug is in the test, not the engine: it counts five sessions and one is a background daemon.',

  /* La cabecera y el pie de cada panel */
  'Contexto usado': 'Context used',
  'Lo que ha tocado en git': 'What it touched in git',
  'Sacar a su propia ventana': 'Pop out to its own window',
  'Cerrar la sesión': 'Close the session',
  'Cerrar el panel': 'Close the pane',
  'Escribe un comando': 'Type a command',
  'Escribe un comando o un prompt': 'Type a command or a prompt',
  '✓ Turno terminado': '✓ Turn finished',

  /* La barra de arriba, la ventana y el pie */
  'Minimizar': 'Minimise',
  'Lo que está sonando': 'What\'s playing',
  'Anterior': 'Previous',
  'Pausa': 'Pause',
  'Modo emisión: tapa rutas, claves y datos personales (Ctrl+Mayús+E)': 'Streaming mode: covers paths, keys and personal data (Ctrl+Shift+E)',
  'Llamar al Asistente (Ctrl+Mayús+A)': 'Call the Assistant (Ctrl+Shift+A)',
  'Cerrar las terminales: mata a sus agentes': 'Close the terminals: kills their agents',
  'Tira estrecha': 'Narrow strip',
  '0 terminales ConPTY activas · 0 errores': '0 ConPTY terminals active · 0 errors',
  '4 terminales ConPTY activas · 0 errores': '4 ConPTY terminals active · 0 errors',
  'Ctrl+Mayús+? = Atajos': 'Ctrl+Shift+? = Shortcuts',
  '1,2 GB': '1.2 GB',

  /* Los avisos que salen al pulsar */
  'Emisión encendida: se tapan rutas y nombres.': 'Streaming on: paths and names are covered.',
  'Los objetivos de hoy, siempre a la vista.': 'Today\'s goals, always in sight.',
  'Aquí se elige cómo se reparten los paneles en la Cabina.': 'This is where you choose how panes are laid out in the Cockpit.',
  'CPU, memoria y agentes de Adeorq, no de todo el equipo.': 'CPU, memory and agents for Adeorq alone, not the whole machine.',
  'El Capataz vive en el Panel. Ctrl+Mayús+A desde la Cabina.': 'The Foreman lives in the Dashboard. Ctrl+Shift+A from the Cockpit.',
  'En el programa pide confirmación: cerrar mata a los agentes que estén trabajando.': 'In the app it asks first: closing kills any agents that are working.',
  'Apartada: sale del mosaico pero sigue viva y trabajando.': 'Set aside: it leaves the mosaic but stays alive and working.',

  /* El Panel */
  'Aún en pie, Munito.': 'Still up, Munito.',
  '3 sesiones en marcha y nada pendiente de ti.': '3 sessions running and nothing on your plate.',
  'en 17 proyectos': 'across 17 projects',
  'Pídeme el tablero: "ábreme las sesiones del panel de Orquio" o "en Layco: Antigravity al frontend y un Claude al backend para el formulario de pago"': 'Ask me for the board: "open the sessions of the Orquio dashboard" or "in Layco: Antigravity on the frontend and a Claude on the backend for the payment form"',
  'Nace con AGENTS.md (tus reglas), docs/METAS.md, .gitignore y git, y aparece solo en el panel.': 'It starts with AGENTS.md (your rules), docs/METAS.md, .gitignore and git, and shows up in Adeorq on its own.',
  'La misión de hoy': 'Today\'s mission',
  'Lo que has dicho que importa, para que la Cabina lo tenga a la vista.': 'What you said matters, so the Cockpit keeps it in sight.',

  /* El Chat */
  'Adeorq: sesiones y terminales': 'Adeorq: sessions and terminals',
  'Repasar el contraste de la web': 'Check the website\'s contrast',
  'cargo test · el motor de terminales': 'cargo test · the terminal engine',
  'El encuadre de la portada': 'The front page framing',
  'El scroll se comía la última línea': 'The scroll was eating the last line',
  'Migrar el lector de sesiones': 'Migrate the session reader',
  'La guía de uso': 'The user guide',
  '3 archivos sin guardar': '3 uncommitted files',
  'oye, ¿cuánto me está costando de verdad una sesión larga de estas?': 'hey, how much is one of these long sessions really costing me?',
  'Menos de lo que parece, y el motivo es la caché.': 'Less than it looks, and the reason is the cache.',
  'De los 812.000 tokens de entrada de esta conversación,': 'Of the 812,000 input tokens in this conversation,',
  '786.000 han salido de caché': '786,000 came from the cache',
  '. La tarifa por millón que anuncian es la del token nuevo, y aquí solo el 3% lo es.': '. The per-million rate they advertise is the price of a fresh token, and here only 3% are fresh.',
  'La cuenta de hoy, por vía:': 'Today\'s cost, by route:',
  '· por el CLI, con tu suscripción: entra en la cuota, 0 €': '· through the CLI, on your subscription: it counts against your quota, €0',
  '· la misma conversación por API: 4,12 €': '· the same conversation through the API: €4.12',
  'entonces lo que encarece no es la longitud': 'so what makes it expensive isn\'t the length',
  'Exacto: es CAMBIAR de tema. Cada vez que abres un archivo nuevo grande, esa parte entra sin caché y se paga entera. Por eso': 'Exactly: it\'s CHANGING topic. Every time you open a big new file, that part comes in uncached and you pay full price for it. That\'s why',
  'a mitad de tarea sale más caro que seguir.': 'mid-task costs more than carrying on.',

  /* La Memoria */
  'La lista de siempre': 'The usual list',
  'El mapa de la bóveda': 'The vault map',
  'El grafo de enlaces': 'The link graph',
  'Volver a leer': 'Reload',
  '281 documentos': '281 documents',
  'Reglas': 'Rules',
  'Diario': 'Journal',
  'Proyectos/Adeorq': 'Projects/Adeorq',
  'Diario/2026-08': 'Journal/2026-08',
  'Adeorq · rumbo del de pago': 'Adeorq · where the paid version is heading',
  'Qué se queda gratis': 'What stays free',
  'Adeorq · el rumbo de la web': 'Adeorq · where the website is heading',
  'Regla X · a la tercera no se insiste': 'Rule X · no third try',
  'Regla AD · nada está hecho hasta ejecutarlo': 'Rule AD · nothing is done until it runs',
  'Reglas/Regla X · a la tercera no se insiste.md': 'Rules/Rule X · no third try.md',
  'Si algo se resiste tras': 'If something still won\'t work after',
  'dos intentos': 'two attempts',
  ', o si digo': ', or if I say',
  'dos veces': 'twice',
  'que eso no es lo que quiero, la culpa deja de ser del código y pasa a ser de la herramienta, la librería o el stack.': 'that it isn\'t what I want, the blame moves from the code to the tool, the library or the stack.',
  'Cambiar un parámetro o repetir el mismo enfoque con otra sintaxis es el MISMO intento, no uno nuevo.': 'Changing a parameter or repeating the same approach with different syntax is the SAME attempt, not a new one.',
  'Qué hacer al llegar a dos': 'What to do when you hit two',
  'Parar y nombrar la pared en voz alta.': 'Stop and name the wall out loud.',
  'Mirar qué se usa hoy para ese problema concreto.': 'Look up what people use today for that exact problem.',
  'Proponer 2 o 3 caminos amplios, no micro-ajustes.': 'Propose 2 or 3 broad paths, not micro-tweaks.',
  'Aparcar con su condición de desbloqueo también vale. Y lo mismo aplica cuando el problema es de gusto y no de error.': 'Parking it, with the condition that would unblock it, also counts. And the same applies when the problem is one of taste, not a bug.',
  'Enlaza con': 'Links to',
  'Regla AA · empezar por lo que está mal': 'Rule AA · start with what\'s wrong',
  'Regla O · ambición por defecto': 'Rule O · ambition by default',

  /* La Agenda */
  'Lo que viene, lo que se te ocurrió y lo que toca después.': 'What\'s coming, what you thought of and what\'s next.',
  'faltan 2 días': '2 days left',
  'AI Act art. 50: el Chat debe identificarse como IA': 'AI Act art. 50: the Chat must identify itself as an AI',
  'Pasos siguientes': 'Next steps',
  'VIERNES 9 DE OCTUBRE': 'FRIDAY 9 OCTOBER',
  'Marcar': 'Mark as done',
  'terminar la maqueta del panel': 'finish the app mockup',
  'Lo que quieres tener hecho hoy': 'What you want done today',
  'Viven en un archivo, así que un agente puede tacharlos cuando estén hechos.': 'They live in a file, so an agent can tick them off when they\'re done.',
  'Lo que viene': 'Coming up',
  'Con su fecha, y lo que falta para cada cosa.': 'With their dates, and how long until each one.',
  'AI Act art. 50: avisar de que es una IA': 'AI Act art. 50: say that it\'s an AI',
  'Renovar munito.dev': 'Renew munito.dev',
  'Dominios · 2026-09-04': 'Domains · 2026-09-04',
  'Revisar la caché de C:\\ct': 'Check the C:\\ct cache',
  'Mantenimiento · 2026-08-27': 'Maintenance · 2026-08-27',
  'La bandeja': 'The inbox',
  'Lo que se te ocurre al vuelo, y lo que proponen los agentes. Se acepta o se descarta: nunca deciden ellos.': 'What comes to you on the fly, and what the agents suggest. You accept it or drop it: they never decide.',
  'Un navegador dentro del Lienzo': 'A browser inside the Canvas',
  'propuesta del Capataz · Adeorq': 'suggested by the Foreman · Adeorq',
  'Que la Cabina recuerde el reparto por proyecto': 'Have the Cockpit remember the layout per project',
  'idea al vuelo · Adeorq': 'idea on the fly · Adeorq',
  'Exportar la sesión a Markdown': 'Export the session to Markdown',
  'Lo que dejó apuntado la última sesión de cada proyecto.': 'What each project\'s last session left written down.',
  'Llevar la maqueta a la landing': 'Put the mockup on the landing page',
  'Adeorq · lo dejó la sesión de hoy': 'Adeorq · left by today\'s session',
  'Medir el arranque en frío': 'Measure the cold start',
  'src-tauri · lo dejó ayer': 'src-tauri · left yesterday',

  /* Las Cuentas */
  'Cada cuenta es un acceso distinto del mismo CLI, con su propia carpeta. Las terminales nuevas nacen con la que dejes por defecto.': 'Each account is a separate login to the same CLI, with its own folder. New terminals open with whichever one you set as default.',
  'de 9 programas instalados': 'out of 9 installed programs',
  'Claude Code · vuelve a las 9:00': 'Claude Code · resets at 9:00',
  'la de por defecto': 'the default one',
  'POR DEFECTO': 'DEFAULT',
  'una cuenta': 'one account',
  'Este CLI no publica el gasto en la máquina, así que no hay barras que enseñar.': 'This CLI doesn\'t record its usage on your machine, so there are no bars to show.',
  'Se guardan cifradas en tu máquina y no vuelven nunca al panel. Adeorq funciona sin ellas: usa la cuenta que ya tienes.': 'They\'re stored encrypted on your machine and never travel back to the interface. Adeorq works without them: it uses the account you already have.',
  'Los que no tienes': 'The ones you don\'t have',
  'Cada uno con su botón, que abre una terminal y lanza la instalación.': 'Each one has its own button, which opens a terminal and runs the install.',
  'no está en el PATH': 'not on the PATH',

  /* El Lienzo */
  'Mover': 'Move',
  'Imagen': 'Image',
  'Arrastra las piezas. Doble clic en una nota para escribir.': 'Drag the pieces. Double-click a note to type.',
  'La maqueta va a la landing cuando Munir la apruebe.': 'The mockup goes on the landing page once Munir approves it.',
  'Los temas salen de App.css, no copiados a mano.': 'The themes come from App.css, not copied by hand.',
  'Barrer el scratchpad': 'Sweep the scratchpad',
  '› ¿qué falta?': '› what\'s left?',
  'Las cuatro vistas y el Ctrl+K.': 'The four views and Ctrl+K.',

  /* Los Comandos y la paleta (Ctrl+K) */
  'Todo lo que hace la app, a un Ctrl+K. Escribe y filtra.': 'Everything the app does, one Ctrl+K away. Type to filter.',
  'Buscar un comando': 'Search for a command',
  'Abrir una sesión nueva': 'Open a new session',
  'Abrir todo el proyecto': 'Open the whole project',
  'Cerrar la sesión activa': 'Close the active session',
  'Dividir el panel a la derecha': 'Split the pane to the right',
  'Dividir el panel abajo': 'Split the pane down',
  'Maximizar el panel activo': 'Maximise the active pane',
  'Sacar el panel a su ventana': 'Pop the pane out to its own window',
  'Pedirle el tablero al Capataz': 'Ask the Foreman for the board',
  'Tapar rutas y nombres (emitir)': 'Cover paths and names (streaming)',
  'Pantalla de pánico': 'Panic screen',
  'Ir a': 'Go to',
  'Ir al Panel': 'Go to the Dashboard',
  'Ir a la Cabina': 'Go to the Cockpit',
  'Ir a la Agenda': 'Go to the Agenda',
  'Ver todos los atajos': 'See all shortcuts',
  'Qué quieres hacer': 'What do you want to do',
  '↑↓ para moverte · Enter para ir · Esc para cerrar': '↑↓ to move · Enter to go · Esc to close',
  'Ctrl+Mayús+O': 'Ctrl+Shift+O',
  'Ctrl+Mayús+→': 'Ctrl+Shift+→',
  'Ctrl+Mayús+↓': 'Ctrl+Shift+↓',
  'Ctrl+Mayús+F': 'Ctrl+Shift+F',
  'Ctrl+Mayús+V': 'Ctrl+Shift+V',
  'Ctrl+Mayús+A': 'Ctrl+Shift+A',
  'Ctrl+Mayús+E': 'Ctrl+Shift+E',
  'Ctrl+Mayús+P': 'Ctrl+Shift+P',
  'Ctrl+Mayús+?': 'Ctrl+Shift+?',

  /* Los Ajustes: los temas con nombre español */
  'Los 32 temas de la app, con sus colores de verdad.': 'The app\'s 32 themes, in their real colours.',
  'Solo cambia el juego de colores: el cristal, el desenfoque y la forma se quedan igual. Clic para probarlo aquí mismo.': 'Only the colour set changes: the glass, the blur and the shape stay the same. Click to try it right here.',
  'Azul': 'Blue',
  'Grafito': 'Graphite',
  'Violeta': 'Violet',
  'Verde': 'Green',
  'Carmín': 'Crimson',
  'Ámbar': 'Amber',
  'Océano': 'Ocean',
  'Neón': 'Neon',
  'Drácula': 'Dracula',
  'Esmeralda': 'Emerald',
  'Ocaso': 'Dusk',
  'Turquesa': 'Turquoise',
  'Negro': 'Black',
  'Tinta': 'Ink',
  'Ciruela': 'Plum',
  'Arena': 'Sand',
  'Papel': 'Paper',
  'Claro': 'Light',

  /* La cabecera del banco de pruebas (fuera del iframe) */
  'La maqueta del panel': 'The app mockup',
  'Rehecha desde cero contra el codigo de la app. Los temas, las medidas y los iconos salen de': 'Rebuilt from scratch against the app\'s code. The themes, the sizes and the icons come from',
  ', no estan copiados a ojo.': ', not copied by eye.',
  'Vista': 'View',

  /* El Panel: el saludo cambia con la hora (demo.js lo escribe en un solo nodo) */
  'Buenos días, Munito.': 'Good morning, Munito.',
  'Buenas tardes, Munito.': 'Good afternoon, Munito.',
  'Buenas noches, Munito.': 'Good evening, Munito.',
  'Pídele el tablero en cristiano: él propone el plan (sesiones, Claudes, terminales, Antigravity) y no ejecuta nada sin tu OK. En la Cabina: Ctrl+Mayús+A.': 'Ask it for the board in plain words: it proposes the plan (sessions, Claudes, terminals, Antigravity) and runs nothing without your OK. In the Cockpit: Ctrl+Shift+A.',

  /* La Memoria: el «y» suelto entre los dos enlaces de la nota */
  'y': 'and',

  /* La paleta de comandos (Ctrl+K, mandos.js) */
  'Ir al Lienzo': 'Go to the Canvas',
  'Ir a Cuentas': 'Go to Accounts',
  'Ir a Comandos': 'Go to Commands',
  'Ir a Ajustes': 'Go to Settings',
  'Cambiar el tema': 'Change the theme',
  'No encuentro eso.': 'Can\'t find that.',
  'No encuentro ese comando.': 'Can\'t find that command.',

  /* Abrir una sesión más (mandos.js): los tres paneles nuevos, por turno */
  'Revisar la Agenda': 'Review the Agenda',
  'docs · guía de uso': 'docs · user guide',
  'web · el changelog': 'web · the changelog',
  'Abriendo claude en Adeorq…': 'Opening claude in Adeorq…',
  'Abriendo shell en docs…': 'Opening shell in docs…',
  'Abriendo codex en web…': 'Opening codex in web…',
  'terminal ConPTY lista': 'ConPTY terminal ready',
  'Escribe abajo para empezar.': 'Type below to start.',
  'Sesión nueva en Adeorq. Escribe abajo y contesta.': 'New session in Adeorq. Type below and it replies.',
  'Sesión nueva en docs. Escribe abajo y contesta.': 'New session in docs. Type below and it replies.',
  'Sesión nueva en web. Escribe abajo y contesta.': 'New session in web. Type below and it replies.',
  'En la app el tope es la RAM: cada sesión son unos 200 MB.': 'In the app the limit is your RAM: each session takes about 200 MB.',

  /* La franja de la derecha (lateral.js): Skills · Uso */
  'Arrástralo sobre una terminal para pegarlo, o púlsalo para mandarlo a la que tengas delante.': 'Drag it onto a terminal to paste it, or click it to send it to the one in front of you.',
  'Cierra la sesión: resumen, memoria al día y commits antes de compactar.': 'Closes the session: summary, memory up to date and commits before compacting.',
  'Repite una tarea a intervalos hasta que le digas basta.': 'Repeats a task at intervals until you tell it to stop.',
  'Parallax y scroll premium, con el dial de movimiento de la casa.': 'Premium parallax and scrolling, with the house motion dial.',
  'Mira si una web se encuentra: HTML servido, Core Web Vitals y meta.': 'Checks whether a site can be found: served HTML, Core Web Vitals and meta tags.',
  'Audita las licencias antes de cobrar por nada.': 'Audits the licences before you charge for anything.',
  'El prompt de auditoría de seguridad que lleva cada repo público.': 'The security audit prompt that every public repo carries.',
  'La versión pública y ligera de los efectos al scroll.': 'The public, lightweight version of the scroll effects.',
  'Uso de la semana': 'This week\'s usage',
  '62 % de la cuota · se renueva el lunes a las 9:00': '62% of the quota · renews Monday at 9:00',
  'En el programa esto escribe /fin en la terminal que tengas delante.': 'In the app this types /fin into the terminal in front of you.',
  'En el programa esto escribe /loop en la terminal que tengas delante.': 'In the app this types /loop into the terminal in front of you.',
  'En el programa esto escribe /frontlaxweb en la terminal que tengas delante.': 'In the app this types /frontlaxweb into the terminal in front of you.',
  'En el programa esto escribe /webindex en la terminal que tengas delante.': 'In the app this types /webindex into the terminal in front of you.',
  'En el programa esto escribe /galsas en la terminal que tengas delante.': 'In the app this types /galsas into the terminal in front of you.',
  'En el programa esto escribe /audit-this-project en la terminal que tengas delante.': 'In the app this types /audit-this-project into the terminal in front of you.',
  'En el programa esto escribe /animar-scroll en la terminal que tengas delante.': 'In the app this types /animar-scroll into the terminal in front of you.',

  /* La franja de la derecha: Actividad */
  'Lo que pasa por detrás de la terminal que tienes delante.': 'What goes on behind the terminal in front of you.',
  'modelo': 'model',
  'hace 2 min': '2 min ago',
  'hace 4 min': '4 min ago',
  'hace 5 min': '5 min ago',
  'hace 6 min': '6 min ago',
  'hace 9 min': '9 min ago',
  'Cerró la sesión y dejó sus commits': 'Closed the session and left its commits',
  'Leyó el árbol de la página': 'Read the page tree',
  'web/demo/piezas.css · 14 líneas': 'web/demo/piezas.css · 14 lines',
  '8.712 tokens · 786k de caché': '8,712 tokens · 786k from cache',
  '4 terminales, 1 esperando': '4 terminals, 1 waiting',

  /* La franja de la derecha: Archivos */
  'La carpeta del proyecto que tienes delante. Púlsalo y se abre en un panel.': 'The folder of the project in front of you. Click a file and it opens in a pane.',
  '6,1 kB': '6.1 kB',
  '48,3 kB': '48.3 kB',
  '31,7 kB': '31.7 kB',
  '44,2 kB': '44.2 kB',
  'Se abriría en un panel del mosaico, al lado de las terminales.': 'It would open in a pane of the mosaic, next to the terminals.',
  'Mete la web de tu proyecto en un panel del mosaico, con su localhost de verdad.': 'Puts your project\'s site in a pane of the mosaic, on its real localhost.',

  /* Los botones de la ventana (lateral.js) */
  'En el programa se va a la bandeja: las terminales siguen vivas.': 'In the app it goes to the system tray: the terminals stay alive.',
  'Cerrar la ventana mata a los agentes que estén trabajando: el programa lo pregunta antes.': 'Closing the window kills any agents that are working: the app asks first.',

  /* Los avisos de la Cabina, el riel y el Panel (demo.js) */
  'En la app esto se lo manda al CLI tal cual, sin traducir nada.': 'In the app this goes straight to the CLI, untouched.',
  'La sesión se cerraría del todo.': 'The session would close for good.',
  'El panel se cierra; la sesión sigue viva.': 'The pane closes; the session stays alive.',
  'Enseñaría los archivos que ha tocado esta sesión.': 'It would show the files this session has touched.',
  'Bajaría a la tira de abajo, y el agente sigue trabajando.': 'It would drop to the strip below, and the agent keeps working.',
  'Saldría a su propia ventana, sin cortar la sesión.': 'It would pop out to its own window, without cutting the session.',
  'Abrirías Adeorq con sus sesiones. Aquí es una maqueta.': 'You\'d open Adeorq with its sessions. This is a mockup.',
  'Abrirías src-tauri con sus sesiones. Aquí es una maqueta.': 'You\'d open src-tauri with its sessions. This is a mockup.',
  'Abrirías web con sus sesiones. Aquí es una maqueta.': 'You\'d open web with its sessions. This is a mockup.',
  'Abrirías docs con sus sesiones. Aquí es una maqueta.': 'You\'d open docs with its sessions. This is a mockup.',
  'Irías a Adeorq.': 'You\'d go to Adeorq.',
  'Irías a src-tauri.': 'You\'d go to src-tauri.',
  'Irías a web.': 'You\'d go to web.',
  'Irías a docs.': 'You\'d go to docs.',
  'El Capataz propondría el tablero y esperaría tu OK.': 'The Foreman would propose the board and wait for your OK.',
  'Escribe qué quieres montar y el Capataz propone el plan.': 'Write what you want to set up and the Foreman proposes the plan.',
  'Aquí se escribe el encargo para la cuadrilla.': 'This is where you write the brief for the crew.',
  'Emisión apagada: vuelven a verse las rutas.': 'Streaming off: paths are visible again.',

  /* Los avisos de la Agenda, las Cuentas, el Lienzo y los Comandos (vistas.js) */
  'En la app esto vive en un archivo, así que un agente puede tacharlo solo.': 'In the app this lives in a file, so an agent can tick it off on its own.',
  'Abriría la ficha del aviso, con lo que hay que hacer y por qué.': 'It would open the reminder\'s card, with what needs doing and why.',
  'En la app abre el archivo de objetivos en tu editor.': 'In the app it opens the goals file in your editor.',
  'Abriría una terminal nueva con Claude Code.': 'It would open a new terminal with Claude Code.',
  'Abriría una terminal nueva con Codex.': 'It would open a new terminal with Codex.',
  'En la app se abre el acceso de Claude Code en su propia carpeta.': 'In the app this opens the Claude Code login in its own folder.',
  'En la app se abre el acceso de Codex en su propia carpeta.': 'In the app this opens the Codex login in its own folder.',
  'En la app se abre el acceso de Gemini CLI en su propia carpeta.': 'In the app this opens the Gemini CLI login in its own folder.',
  'En la app se abre el acceso de GitHub Copilot en su propia carpeta.': 'In the app this opens the GitHub Copilot login in its own folder.',
  'En la app se abre el acceso de Crush en su propia carpeta.': 'In the app this opens the Crush login in its own folder.',
  'En la app se abre el acceso de Antigravity en su propia carpeta.': 'In the app this opens the Antigravity login in its own folder.',
  'Escribe aquí.': 'Type here.',
  'En la app la pieza se guarda en el archivo del lienzo, y sigue ahí mañana.': 'In the app the piece is saved in the canvas file, and it\'s still there tomorrow.',
  '«Abrir una sesión nueva» — en la app se ejecuta al momento.': '"Open a new session": in the app it runs right away.',
  '«Abrir todo el proyecto» — en la app se ejecuta al momento.': '"Open the whole project": in the app it runs right away.',
  '«Cerrar la sesión activa» — en la app se ejecuta al momento.': '"Close the active session": in the app it runs right away.',
  '«Dividir el panel a la derecha» — en la app se ejecuta al momento.': '"Split the pane to the right": in the app it runs right away.',
  '«Dividir el panel abajo» — en la app se ejecuta al momento.': '"Split the pane down": in the app it runs right away.',
  '«Maximizar el panel activo» — en la app se ejecuta al momento.': '"Maximise the active pane": in the app it runs right away.',
  '«Sacar el panel a su ventana» — en la app se ejecuta al momento.': '"Pop the pane out to its own window": in the app it runs right away.',
  '«Pedirle el tablero al Capataz» — en la app se ejecuta al momento.': '"Ask the Foreman for the board": in the app it runs right away.',
  '«Tapar rutas y nombres (emitir)» — en la app se ejecuta al momento.': '"Cover paths and names (streaming)": in the app it runs right away.',
  '«Pantalla de pánico» — en la app se ejecuta al momento.': '"Panic screen": in the app it runs right away.',
  '«Ir al Panel» — en la app se ejecuta al momento.': '"Go to the Dashboard": in the app it runs right away.',
  '«Ir a la Cabina» — en la app se ejecuta al momento.': '"Go to the Cockpit": in the app it runs right away.',
  '«Ir a la Agenda» — en la app se ejecuta al momento.': '"Go to the Agenda": in the app it runs right away.',
  '«Ver todos los atajos» — en la app se ejecuta al momento.': '"See all shortcuts": in the app it runs right away.',

  /* Los avisos del Chat y de la Memoria (pantallas.js; sus RESPUESTAS no van aquí) */
  'Es la misma sesión: el Chat la enseña limpia y la Cabina en crudo.': 'It\'s the same session: the Chat shows it clean and the Cockpit shows it raw.',
  'En el programa esto abre esa conversación entera desde su transcript.': 'In the app this opens the whole conversation from its transcript.',
  'El mapa y el grafo dibujan los enlaces entre tus notas: eso necesita tu bóveda de verdad.': 'The map and the graph draw the links between your notes: that needs your real vault.',
  'Vuelve a leer la carpeta entera: 281 documentos en 0,4 s.': 'Reads the whole folder again: 281 documents in 0.4 s.',

  /* Lo que contesta la terminal al escribirle (terminal.js). Cada línea es
     una clave, con su adorno delante (└ ✳) tal como se teclea. */
  'pensando': 'thinking',
  'Lanzo la tanda y te cuento.': 'Running the batch, I\'ll let you know.',
  '└ motor::export::wav_16bit espera 48k y el fixture esta a 44,1.': '└ motor::export::wav_16bit expects 48k and the fixture is at 44.1.',
  'Miro el arbol antes de tocar nada.': 'Checking the tree before touching anything.',
  'Los meto en un commit, o prefieres verlos primero?': 'Shall I put them in a commit, or do you want to see them first?',
  'Compila. La app abre en 1,2 s.': 'It compiles. The app opens in 1.2 s.',
  'He medido el contraste de las tres capas que se pisaban.': 'I measured the contrast of the three overlapping layers.',
  '└ El texto sobre la foto se queda en 3,1:1 y el minimo es 4,5:1.': '└ The text over the photo sits at 3.1:1 and the minimum is 4.5:1.',
  '└ web/styles/hero.css · 4 lineas': '└ web/styles/hero.css · 4 lines',
  'Voy con ello.': 'On it.',
  '└ Miro primero que hay antes de cambiar nada.': '└ Looking at what\'s there before changing anything.',
  'Hecho.': 'Done.',
  '└ src/components/TerminalPane.tsx · 3 lineas': '└ src/components/TerminalPane.tsx · 3 lines',
  'Eso toca dos sitios, asi que te lo cuento antes de hacerlo.': 'That touches two places, so I\'m telling you before I do it.',
  'Sigo?': 'Shall I go on?',
  'Te ha preguntado algo: en la app el panel se queda marcado hasta que contestas.': 'It asked you something: in the app the pane stays marked until you answer.',
  'Turno terminado: en la app el panel se enciende para que lo veas de lejos.': 'Turn finished: in the app the pane lights up so you can spot it from a distance.',

  /* Las respuestas del Chat (pantallas.js, RESPUESTAS): se traducen enteras antes de teclearlas */
  'Voy. Te lo dejo medido, no a ojo: abro los dos archivos, comparo y te digo qué cambia en pantalla antes de tocar nada.': 'On it. I\'ll measure it, not eyeball it: I open both files, compare them and tell you what changes on screen before touching anything.',
  'Hecho. Eran tres capas pisándose y la de en medio no llegaba al mínimo legible. Lo he aplanado contra el tema, sin cambiar el tono.': 'Done. Three layers were stepping on each other and the middle one did not reach the legibility minimum. I flattened it against the theme, without changing the tone.',
  'Eso ya está resuelto desde el arreglo del jueves, así que antes de repetirlo mira qué versión tienes corriendo: puede ser un binario viejo.': 'That has been solved since Thursday\'s fix, so before redoing it check which version you are running: it may be an old binary.',
});
